export const project = {
  name: 'Axel One',
  slug: 'axel-one',
  figmaFileKey: '9pbBXxSus03lQbq9ErSCmO',
}

export const screens = [
  {
    slug: 'importing',
    name: 'Price Watch',
    figmaNodeId: '5079:6386',
    status: 'validated',
    component: 'Importing',
    importPath: '@/projects/axel-one/screens/Importing',
  },
  {
    slug: 'flight-deals',
    name: 'Opportunity Found',
    figmaNodeId: '5079:6500',
    status: 'validated',
    component: 'FlightDeals',
    importPath: '@/projects/axel-one/screens/FlightDeals',
  },
  {
    slug: 'home-member',
    name: 'Home',
    figmaNodeId: null,
    status: 'validated',
    component: 'HomeMember',
    importPath: '@/projects/axel-one/screens/HomeMember',
  },
  {
    slug: 'watch-created',
    name: 'Watch Created',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'WatchCreated',
    importPath: '@/projects/axel-one/screens/WatchCreated',
  },
  {
    slug: 'flight-details',
    name: 'Flight Details',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'FlightDetails',
    importPath: '@/projects/axel-one/screens/FlightDetails',
  },
  {
    slug: 'add-details',
    name: 'Add Details',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'AddDetails',
    importPath: '@/projects/axel-one/screens/AddDetails',
  },
  {
    slug: 'select-passenger',
    name: 'Select Passenger',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'SelectPassenger',
    importPath: '@/projects/axel-one/screens/SelectPassenger',
  },
  {
    slug: 'paywall',
    name: 'Paywall',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'Paywall',
    importPath: '@/projects/axel-one/screens/Paywall',
  },
  {
    slug: 'hotel-deals',
    name: 'Hotel Deals Found',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'HotelDeals',
    importPath: '@/projects/axel-one/screens/HotelDeals',
  },
  {
    slug: 'home-hotel-watch',
    name: 'Home Hotel Watch',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'HomeHotelWatch',
    importPath: '@/projects/axel-one/screens/HomeHotelWatch',
  },
  {
    slug: 'trips-empty',
    name: 'Trips Empty',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripsEmpty',
    importPath: '@/projects/axel-one/screens/TripsEmpty',
  },
  {
    slug: 'trips-list',
    name: 'Trips List',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripsList',
    importPath: '@/projects/axel-one/screens/TripsList',
  },
  {
    slug: 'new-trip-input',
    name: 'New Trip Input',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'NewTripInput',
    importPath: '@/projects/axel-one/screens/NewTripInput',
  },
  {
    slug: 'chat-thinking',
    name: 'Chat Thinking',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'ChatThinking',
    importPath: '@/projects/axel-one/screens/ChatThinking',
  },
  {
    slug: 'chat-flights',
    name: 'Chat Flights',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'ChatFlights',
    importPath: '@/projects/axel-one/screens/ChatFlights',
  },
  {
    slug: 'chat-flight-booked',
    name: 'Chat Flight Booked',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'ChatFlightBooked',
    importPath: '@/projects/axel-one/screens/ChatFlightBooked',
  },
  {
    slug: 'chat-hotels',
    name: 'Chat Hotels',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'ChatHotels',
    importPath: '@/projects/axel-one/screens/ChatHotels',
  },
  {
    slug: 'hotel-map',
    name: 'Hotel Map',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'HotelMap',
    importPath: '@/projects/axel-one/screens/HotelMap',
  },
  {
    slug: 'hotel-detail',
    name: 'Hotel Detail',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'HotelDetail',
    importPath: '@/projects/axel-one/screens/HotelDetail',
  },
  {
    slug: 'itinerary-summary',
    name: 'Itinerary Summary',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'ItinerarySummary',
    importPath: '@/projects/axel-one/screens/ItinerarySummary',
  },
  {
    slug: 'trip-paywall',
    name: 'Trip Paywall',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripPaywall',
    importPath: '@/projects/axel-one/screens/TripPaywall',
  },
  {
    slug: 'trip-payment',
    name: 'Trip Payment',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripPayment',
    importPath: '@/projects/axel-one/screens/TripPayment',
  },
  {
    slug: 'trip-confirmation',
    name: 'Trip Confirmation',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripConfirmation',
    importPath: '@/projects/axel-one/screens/TripConfirmation',
  },
  {
    slug: 'trip-flow-interactive',
    name: 'Trip Flow — Interactive',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripFlowInteractive',
    importPath: '@/projects/axel-one/screens/TripFlowInteractive',
  },
  {
    slug: 'scene-new-trip',
    name: 'Turn: New Trip',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripFlowInteractive',
    importPath: '@/projects/axel-one/screens/TripFlowInteractive',
  },
  {
    slug: 'scene-context',
    name: 'Turn: Options',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripFlowInteractive',
    importPath: '@/projects/axel-one/screens/TripFlowInteractive',
  },
  {
    slug: 'scene-cached',
    name: 'Turn: Re-entry',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripFlowInteractive',
    importPath: '@/projects/axel-one/screens/TripFlowInteractive',
  },
  {
    slug: 'scene-updates',
    name: 'Turn: Updates',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripFlowInteractive',
    importPath: '@/projects/axel-one/screens/TripFlowInteractive',
  },
  {
    slug: 'scene-decision',
    name: 'Turn: Confirmed',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'TripFlowInteractive',
    importPath: '@/projects/axel-one/screens/TripFlowInteractive',
  },
  {
    slug: 'walkthrough',
    name: 'Walkthrough',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'Walkthrough',
    importPath: '@/projects/axel-one/screens/Walkthrough',
  },
  {
    slug: 'competitive-comparison',
    name: 'Competitive — Planning',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'CompetitiveComparison',
    importPath: '@/projects/axel-one/screens/CompetitiveComparison',
  },
  {
    slug: 'competitive-ux',
    name: 'Competitive — UX Audit',
    figmaNodeId: null,
    status: 'in-progress',
    component: 'CompetitiveUX',
    importPath: '@/projects/axel-one/screens/CompetitiveUX',
  },
]

export const flows = [
  {
    slug: 'trip-flow',
    name: 'Trip Flow',
    steps: ['trip-flow-interactive', 'trips-list', 'new-trip-input', 'chat-thinking', 'chat-flights', 'chat-flight-booked', 'chat-hotels', 'hotel-map', 'hotel-detail', 'itinerary-summary', 'trip-paywall', 'trip-payment', 'trip-confirmation', 'scene-new-trip', 'scene-context', 'scene-cached', 'scene-updates', 'scene-decision'],
  },
  {
    slug: 'walkthrough-flow',
    name: 'Walkthrough Flow',
    steps: ['walkthrough'],
  },
]

export const components = [
  {
    slug: 'flight-card',
    name: 'FlightCard',
    importPath: '@/components/FlightCard',
    category: 'Card',
    variants: ['default', 'nonstop', 'one-stop'],
    figmaVariants: { default: 'State=Default', nonstop: 'Stops=Nonstop', 'one-stop': 'Stops=OneStop' },
  },
  {
    slug: 'price-chart',
    name: 'PriceChart',
    importPath: '@/components/PriceChart',
    category: 'Chart',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'cta-button',
    name: 'CTAButton',
    importPath: '@/components/CTAButton',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'flight-deal-card',
    name: 'FlightDealCard',
    importPath: '@/components/FlightDealCard',
    category: 'Card',
    variants: ['default', 'one-stop', 'multi-stop', 'best-deal', 'loading', 'hover'],
    figmaVariants: { default: 'State=Default', 'one-stop': 'State=OneStop', 'multi-stop': 'State=MultiStop', 'best-deal': 'State=BestDeal', loading: 'State=Loading', hover: 'State=Hover' },
  },
  {
    slug: 'flight-results-list',
    name: 'FlightResultsList',
    importPath: '@/components/FlightResultsList',
    category: 'List',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'hotel-deal-card',
    name: 'HotelDealCard',
    importPath: '@/components/HotelDealCard',
    category: 'Card',
    variants: ['default', 'best-deal', 'non-refundable', 'loading', 'hover'],
    figmaVariants: { default: 'State=Default', 'best-deal': 'State=BestDeal', 'non-refundable': 'State=NonRefundable', loading: 'State=Loading', hover: 'State=Hover' },
  },
  {
    slug: 'watch-card',
    name: 'WatchCard',
    importPath: '@/components/WatchCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'thinking-bubble',
    name: 'ThinkingBubble',
    importPath: '@/components/ThinkingBubble',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'trip-card',
    name: 'TripCard',
    importPath: '@/components/TripCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'confirmed-flight-card',
    name: 'ConfirmedFlightCard',
    importPath: '@/components/ConfirmedFlightCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'price-breakdown-card',
    name: 'PriceBreakdownCard',
    importPath: '@/components/PriceBreakdownCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'confirmed-booking-card',
    name: 'ConfirmedBookingCard',
    importPath: '@/components/ConfirmedBookingCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'order-summary-card',
    name: 'OrderSummaryCard',
    importPath: '@/components/OrderSummaryCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'paywall-card',
    name: 'PaywallCard',
    importPath: '@/components/PaywallCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'hotel-map-peek-card',
    name: 'HotelMapPeekCard',
    importPath: '@/components/HotelMapPeekCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'saved-payment-card',
    name: 'SavedPaymentCard',
    importPath: '@/components/SavedPaymentCard',
    category: 'Card',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'axel-panel',
    name: 'AxelPanel',
    importPath: '@/components/AxelPanel',
    category: 'UI',
    variants: ['default', 'typing', 'compact'],
    figmaVariants: { default: 'State=Default', typing: 'State=Typing', compact: 'State=Compact' },
  },
  {
    slug: 'step-progress',
    name: 'StepProgress',
    importPath: '@/components/StepProgress',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'axel-chat-container',
    name: 'AxelChatContainer',
    importPath: '@/components/AxelChatContainer',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'bottom-nav',
    name: 'BottomNav',
    importPath: '@/components/BottomNav',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'status-bar',
    name: 'StatusBar',
    importPath: '@/components/StatusBar',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'home-indicator',
    name: 'HomeIndicator',
    importPath: '@/components/HomeIndicator',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'quick-option-pills',
    name: 'QuickOptionPills',
    importPath: '@/components/QuickOptionPills',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
  {
    slug: 'trip-input-bar',
    name: 'TripInputBar',
    importPath: '@/components/TripInputBar',
    category: 'UI',
    variants: ['default'],
    figmaVariants: { default: 'State=Default' },
  },
]

// File mappings for iteration system (type:slug → file info)
export const fileMappings = {
  'screen:importing': { dir: 'src/projects/axel-one/screens', baseName: 'Importing' },
  'screen:flight-deals': { dir: 'src/projects/axel-one/screens', baseName: 'FlightDeals' },
  'screen:home-member': { dir: 'src/projects/axel-one/screens', baseName: 'HomeMember' },
  'screen:watch-created': { dir: 'src/projects/axel-one/screens', baseName: 'WatchCreated' },
  'screen:flight-details': { dir: 'src/projects/axel-one/screens', baseName: 'FlightDetails' },
  'screen:add-details': { dir: 'src/projects/axel-one/screens', baseName: 'AddDetails' },
  'screen:select-passenger': { dir: 'src/projects/axel-one/screens', baseName: 'SelectPassenger' },
  'screen:paywall': { dir: 'src/projects/axel-one/screens', baseName: 'Paywall' },
  'screen:hotel-deals': { dir: 'src/projects/axel-one/screens', baseName: 'HotelDeals' },
  'screen:home-hotel-watch': { dir: 'src/projects/axel-one/screens', baseName: 'HomeHotelWatch' },
  'screen:trips-empty': { dir: 'src/projects/axel-one/screens', baseName: 'TripsEmpty' },
  'screen:trips-list': { dir: 'src/projects/axel-one/screens', baseName: 'TripsList' },
  'screen:new-trip-input': { dir: 'src/projects/axel-one/screens', baseName: 'NewTripInput' },
  'screen:chat-thinking': { dir: 'src/projects/axel-one/screens', baseName: 'ChatThinking' },
  'screen:chat-flights': { dir: 'src/projects/axel-one/screens', baseName: 'ChatFlights' },
  'screen:chat-flight-booked': { dir: 'src/projects/axel-one/screens', baseName: 'ChatFlightBooked' },
  'screen:chat-hotels': { dir: 'src/projects/axel-one/screens', baseName: 'ChatHotels' },
  'screen:hotel-map': { dir: 'src/projects/axel-one/screens', baseName: 'HotelMap' },
  'screen:hotel-detail': { dir: 'src/projects/axel-one/screens', baseName: 'HotelDetail' },
  'screen:itinerary-summary': { dir: 'src/projects/axel-one/screens', baseName: 'ItinerarySummary' },
  'screen:trip-paywall': { dir: 'src/projects/axel-one/screens', baseName: 'TripPaywall' },
  'screen:trip-payment': { dir: 'src/projects/axel-one/screens', baseName: 'TripPayment' },
  'screen:trip-confirmation': { dir: 'src/projects/axel-one/screens', baseName: 'TripConfirmation' },
  'screen:trip-flow-interactive': { dir: 'src/projects/axel-one/screens', baseName: 'TripFlowInteractive' },
  'screen:walkthrough': { dir: 'src/projects/axel-one/screens', baseName: 'Walkthrough' },
  'screen:competitive-comparison': { dir: 'src/projects/axel-one/screens', baseName: 'CompetitiveComparison' },
  'screen:competitive-ux': { dir: 'src/projects/axel-one/screens', baseName: 'CompetitiveUX' },
  'component:flight-card': { dir: 'src/components', baseName: 'FlightCard' },
  'component:price-chart': { dir: 'src/components', baseName: 'PriceChart' },
  'component:cta-button': { dir: 'src/components', baseName: 'CTAButton' },
  'component:flight-deal-card': { dir: 'src/components', baseName: 'FlightDealCard' },
  'component:flight-results-list': { dir: 'src/components', baseName: 'FlightResultsList' },
  'component:hotel-deal-card': { dir: 'src/components', baseName: 'HotelDealCard' },
  'component:watch-card': { dir: 'src/components', baseName: 'WatchCard' },
  'component:thinking-bubble': { dir: 'src/components', baseName: 'ThinkingBubble' },
  'component:trip-card': { dir: 'src/components', baseName: 'TripCard' },
  'component:confirmed-flight-card': { dir: 'src/components', baseName: 'ConfirmedFlightCard' },
  'component:price-breakdown-card': { dir: 'src/components', baseName: 'PriceBreakdownCard' },
  'component:confirmed-booking-card': { dir: 'src/components', baseName: 'ConfirmedBookingCard' },
  'component:order-summary-card': { dir: 'src/components', baseName: 'OrderSummaryCard' },
  'component:paywall-card': { dir: 'src/components', baseName: 'PaywallCard' },
  'component:hotel-map-peek-card': { dir: 'src/components', baseName: 'HotelMapPeekCard' },
  'component:saved-payment-card': { dir: 'src/components', baseName: 'SavedPaymentCard' },
  'component:axel-panel': { dir: 'src/components', baseName: 'AxelPanel' },
  'component:step-progress': { dir: 'src/components', baseName: 'StepProgress' },
  'component:axel-chat-container': { dir: 'src/components', baseName: 'AxelChatContainer' },
  'component:bottom-nav': { dir: 'src/components', baseName: 'BottomNav' },
  'component:status-bar': { dir: 'src/components', baseName: 'StatusBar' },
  'component:home-indicator': { dir: 'src/components', baseName: 'HomeIndicator' },
  'component:quick-option-pills': { dir: 'src/components', baseName: 'QuickOptionPills' },
  'component:trip-input-bar': { dir: 'src/components', baseName: 'TripInputBar' },
}

// Maps component slugs to the screens they appear in and how to inject them
export const componentScreenMap = {
  'flight-card': [
    { screenSlug: 'flight-deals', screenLabel: 'Flight Deals', templateImport: '@/templates/FlightDealsTemplate', propName: 'FlightCardComponent' },
  ],
  'price-chart': [
    { screenSlug: 'importing', screenLabel: 'Price Watch', templateImport: '@/templates/ImportingTemplate', propName: 'PriceChartComponent' },
  ],
  'cta-button': [
    { screenSlug: 'flight-deals', screenLabel: 'Flight Deals', templateImport: '@/templates/FlightDealsTemplate', propName: 'CTAButtonComponent' },
    { screenSlug: 'importing', screenLabel: 'Price Watch', templateImport: '@/templates/ImportingTemplate', propName: 'CTAButtonComponent' },
  ],
  'flight-deal-card': [
    { screenSlug: 'deals-list', screenLabel: 'List', templateImport: '@/templates/DealsListTemplate', propName: 'FlightDealCardComponent' },
    { screenSlug: 'flight-deal-detail', screenLabel: 'Detail', templateImport: '@/templates/FlightDealDetailTemplate', propName: 'FlightDealCardComponent' },
  ],
  'flight-results-list': [
    { screenSlug: 'deals-list', screenLabel: 'Deals List', templateImport: '@/templates/DealsListTemplate', propName: 'FlightResultsListComponent' },
  ],
  'hotel-deal-card': [
    { screenSlug: 'hotel-deals', screenLabel: 'List', templateImport: '@/templates/HotelDealsTemplate', propName: 'HotelDealCardComponent' },
    { screenSlug: 'hotel-deal-detail', screenLabel: 'Detail', templateImport: '@/templates/HotelDealDetailTemplate', propName: 'HotelDealCardComponent' },
  ],
  'watch-card': [
    { screenSlug: 'home-watch', screenLabel: 'Home Watch', templateImport: '@/templates/HomeWatchTemplate', propName: 'WatchCardComponent' },
  ],
}

// Default Figma page targets for capture
export const captureTargets = [
  { label: 'Captures', value: 'Captures' },
  { label: 'Flow — Flight Hold', value: 'Flow — Flight Hold' },
  { label: 'Flow — Trip Flow', value: 'Flow — Trip Flow' },
]

export function getFigmaUrl(nodeId) {
  if (!nodeId) return null
  return `https://www.figma.com/design/${project.figmaFileKey}?node-id=${nodeId.replace(':', '-')}`
}

export function getFigmaFileUrl() {
  return `https://www.figma.com/design/${project.figmaFileKey}`
}
